# Generated by Django 5.0.2 on 2024-03-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='unknown', max_length=255)),
                ('article', models.CharField(default='unknown', max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(default='unknown', max_length=255)),
                ('display_type', models.CharField(default='constructor', max_length=255)),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
    ]
